### ISSUE TITLE
How can I customize the navbar?

### ISSUE THREAD

**Issue by qwertie** [franciscop/picnic#144]
As a newbie web developer making a simple (but multilingual) site, I tried out 12 different [css libraries](http://sixrevisions.com/css/small-css-frameworks/) and I hereby declare that Picnic is my favorite. However, 

- I would prefer a nav bar that is not fixed (that disappears when you scroll down). 
- On my site I need two navbars, a double-high navbar, or variable-height navbar in order to show a list of available translations of the current page, in addition to the list of site areas. With Picnic, a second `<nav>` element replaces the first one.

How can I do this?

**Comment by franciscop** [comment]
Thanks!

Both can be done, the first issue like this:

```css
nav {
  position: absolute;
}
```

[See demo](https://jsfiddle.net/franciscop/x4j7f427/)

The second nav... is not as easy. You could do something like this though:

```html
<nav>...</nav>
<nav class="translations">...</nav>
```

```css
nav.translations {
  top: 3em;

  /* Optional: avoid shadowing other nav */
  box-shadow: none;
  border-bottom: 1px solid #ccc;
}
```

[See example](https://jsfiddle.net/franciscop/vuq0mwpo/)

However the responsive versions might get screwed up depending on how you implement them (or if you implement them at all).
